---
blobstore:
  provider: s3
  options:
    bucket_name: boshreleases
    iam_name: boshblobs-download
    s3_owner: drnicwilliams@gmail.com
    encryption_key: asdfasfdasdfasdf
final_name: gitlabhq
