#!/bin/bash

# Control script to start/stop gitolite job on a BOSH controlled VM

source /var/vcap/packages/common/utils.sh
redirect_output 'gitolite_ctl'

# Setup git user & env variables
/var/vcap/jobs/gitolite/bin/setup_gitolite

RUN_DIR=/var/vcap/sys/run/gitolite
LOG_DIR=/var/vcap/sys/log/gitolite
STORE=/var/vcap/store/gitolite
PIDFILE=$RUN_DIR/gitolite.pid

export PATH=/var/vcap/packages/perl/bin:$PATH
export PATH=/var/vcap/packages/git/bin:$PATH

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $STORE

    echo $$ > $PIDFILE

    # exec $COMMAND >>$LOG_DIR/gitolite.stdout.log 2>>$LOG_DIR/gitolite.stderr.log
    echo "gitolite: No command to run yet!"
    exit 1
    ;;

  stop)
    echo "Stopping gitolite"
    kill_and_wait $PIDFILE
    ;;

  logs)
    cat $LOG_DIR/*
    ;;

  tail)
    tail -f $LOG_DIR/*
    ;;

  clearlogs)
    rm $LOG_DIR/*
    ;;

  *)
  echo "Usage: gitolite_ctl {start|stop|logs|tail|clearlogs}" ;;
esac
exit 0
