#!/bin/bash

# Setup env vars and folders for the gitlabhq_rack_ctl script
source /var/vcap/jobs/gitolite/bin/ctl_setup.sh

# Override ctl_setup.sh defaults:
redirect_output 'nginx'
PIDFILE=$RUN_DIR/nginx.pid

case $1 in

  start)
    pid_guard $PIDFILE "gitolite nginx"

    # Setup git user & env variables
    source /var/vcap/jobs/gitolite/bin/setup_gitolite
    
    link_job_file config/dot.gitolite.rc $GIT_HOME/.gitolite.rc
    
    echo $$ > $PIDFILE

    exec /var/vcap/packages/nginx_next/sbin/nginx \
         -c /var/vcap/jobs/gitolite/config/nginx.conf \
         >>$LOG_DIR/nginx.stdout.log \
         2>>$LOG_DIR/nginx.stderr.log

    ;;

  stop)
    echo "Stopping nginx"
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}"

    ;;

esac
