#!/bin/bash

RUN_DIR=/var/vcap/sys/run/gitolite
LOG_DIR=/var/vcap/sys/log/gitolite
PIDFILE=$RUN_DIR/nginx.pid

source /var/vcap/packages/common/utils.sh
redirect_output 'gitolite_nginx'

# Setup git user & env variables
/var/vcap/jobs/gitolite/bin/setup_gitolite

case $1 in

  start)
    pid_guard $PIDFILE "Nginx"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    exec /var/vcap/packages/nginx_next/sbin/nginx \
         -c /var/vcap/jobs/gitolite/config/nginx.conf \
         >>$LOG_DIR/nginx.stdout.log \
         2>>$LOG_DIR/nginx.stderr.log

    ;;

  stop)
    echo "Stopping nginx"
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}"

    ;;

esac
