---
jobs:
  - <%= job_name %>
properties:
  webapp:
    package: rackapp
    use_nginx: 1
    appstack: puma
    puma:
      threads:
        min: 0
        max: 20
    migrate: 1
    migration_command: rake db:migrate
